#Imagen microsoft
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 as builder
#Creacion de Directorio de trabajo
WORKDIR /Vote
COPY Vote/Vote.csproj .
RUN dotnet restore
#Copia de  Directorios a Contenedor
COPY /Vote .
RUN dotnet publish -c Release -o /out Vote.csproj

# Imagen microsoft
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
#Directorio de trabajo
WORKDIR /app
ENTRYPOINT ["dotnet", "Vote.dll"]

COPY --from=builder /out .