#Imagen Microsoft
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 as builder
#Creacion de directirios de trabajo
WORKDIR /Worker
COPY Worker/Worker.csproj .
RUN dotnet restore
#Copia de archivos al contenedor
COPY /Worker .
RUN dotnet publish -c Release -o /out Worker.csproj

# Imagen microsoft
FROM mcr.microsoft.com/dotnet/core/runtime:3.1
#Creacion de directorio de trabajo
WORKDIR /app
ENTRYPOINT ["dotnet", "Worker.dll"]
#Copia de archivos al contenedor
COPY --from=builder /out .